entity_lock.settings:
  type: config_object
  label: 'Entity Lock settings'
  mapping:
    locked_entities:
      type: sequence
      label: 'Locked entities'
      sequence:
        type: mapping
        label: 'Locked entity entry'
        mapping:
          entity_type:
            type: string
            label: 'Entity type machine name'
          entity_id:
            type: string
            label: 'Entity ID'
          reason:
            type: string
            label: 'Reason for locking'
