/**
 * CharacterDevelopmentScreen — `read / r-dev`
 *
 * Reads back the accumulated character development log — the output of
 * repeated `s-chardev` (Generate Character Development) AI passes, one
 * entry per session.
 *
 * Data source: `field_development[]` paragraph collection on the character
 * node, ordered by `field_session`. Until that Drupal paragraph type is
 * wired, this screen uses `majorPlotActions[]` as a proxy and shows a
 * clear empty state when neither is populated.
 *
 * Design reference: /project/Character Development.html
 */

import * as React from 'react';
import type { ScreenProps } from '../ScreenRouter';
import { Icon } from '../atoms';
import { useConsoleData, playerCharacters } from '../ConsoleContext';
import type { DrupalCharacter } from '../ConsoleContext';

/* ────────────────────────────────────────────────────────────
   Picker
   ──────────────────────────────────────────────────────────── */

function CharPicker({
  roster, selectedId, onSelect,
}: {
  roster: DrupalCharacter[];
  selectedId: string | null;
  onSelect: (id: string) => void;
}): React.ReactElement {
  return (
    <aside className="char-picker">
      <ul className="char-picker-list">
        {roster.map(c => {
          const initials = c.title.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase();
          return (
            <li key={c.id}>
              <button
                type="button"
                className={`char-picker-item${c.id === selectedId ? ' active' : ''}`}
                onClick={() => onSelect(c.id)}
              >
                <span className="char-pip">
                  {c.imageUrl
                    ? <img src={c.imageUrl} alt={c.title} style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '50%' }} />
                    : initials}
                </span>
                <span className="char-pip-meta">
                  <span className="char-pip-name">{c.title}</span>
                  {c.characterClass != null && (
                    <span className="char-pip-class">
                      {c.characterClass}{c.level != null ? ` ${c.level}` : ''}
                    </span>
                  )}
                </span>
              </button>
            </li>
          );
        })}
      </ul>
    </aside>
  );
}

/* ────────────────────────────────────────────────────────────
   Empty state
   ──────────────────────────────────────────────────────────── */

function EmptyArc({ char }: { char: DrupalCharacter }): React.ReactElement {
  return (
    <div style={{
      padding: '40px 32px', textAlign: 'center',
      border: '1px dashed var(--rule)', borderRadius: 8, marginTop: 24,
    }}>
      <Icon name="scroll" size={36} style={{ color: 'var(--brass-dim)', display: 'block', margin: '0 auto 14px' }} />
      <p style={{
        fontFamily: 'var(--font-display)', fontSize: 13, fontWeight: 700,
        letterSpacing: '0.06em', color: 'var(--brass)', marginBottom: 8,
      }}>
        No development arc for {char.title} yet
      </p>
      <p style={{ fontFamily: 'var(--font-body)', fontStyle: 'italic', fontSize: 14, color: 'var(--ink-dim)', maxWidth: '48ch', margin: '0 auto 20px' }}>
        Development entries are generated by the AI after each session. Use
        Generate Character Development from the Stories section to build this arc.
      </p>
      <div style={{
        display: 'inline-flex', alignItems: 'center', gap: 8, padding: '10px 16px',
        background: 'var(--canvas-raised)', border: '1px solid var(--rule)', borderRadius: 6,
        fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--ink-dim)',
      }}>
        <Icon name="story" size={11} style={{ color: 'var(--brass-dim)' }} />
        Stories &rarr; Work with Story Series &rarr; Generate Character Development
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────
   Beat entry (major plot action as a development note)
   ──────────────────────────────────────────────────────────── */

function BeatEntry({
  index, text, expanded, onToggle,
}: {
  index: number;
  text: string;
  expanded: boolean;
  onToggle: () => void;
}): React.ReactElement {
  /* First sentence is the headline; remainder is the body */
  const dot   = text.indexOf('. ');
  const headline = dot > 0 ? text.slice(0, dot + 1) : text;
  const body     = dot > 0 ? text.slice(dot + 2) : '';

  return (
    <div style={{
      display: 'grid', gridTemplateColumns: '32px 1fr',
      gap: 16, paddingBottom: 20,
    }}>
      {/* Spine dot */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: 4 }}>
        <div style={{
          width: 12, height: 12, borderRadius: 9999, flexShrink: 0,
          background: 'var(--canvas-raised)', border: '2px solid var(--brass)',
          boxShadow: '0 0 6px #c9a96e4d',
        }} />
        <div style={{ flex: 1, width: 1, background: 'var(--rule)', marginTop: 6 }} />
      </div>

      {/* Content */}
      <div style={{
        background: 'var(--canvas-raised)', border: '1px solid var(--rule)',
        borderRadius: 8, overflow: 'hidden',
      }}>
        <button
          type="button"
          onClick={onToggle}
          style={{
            display: 'flex', alignItems: 'flex-start', gap: 12,
            width: '100%', background: 'none', border: 'none', cursor: 'pointer',
            padding: '14px 16px', textAlign: 'left',
          }}
        >
          <span style={{
            fontFamily: 'var(--font-mono)', fontSize: 9, color: 'var(--brass-dim)',
            letterSpacing: '0.1em', flexShrink: 0, paddingTop: 3,
          }}>
            {String(index + 1).padStart(2, '0')}
          </span>
          <span style={{
            fontFamily: 'var(--font-body)', fontSize: 14,
            color: 'var(--ink)', lineHeight: 1.5, flex: 1,
          }}>
            {headline}
          </span>
          {body && (
            <Icon
              name={expanded ? 'chevronDown' : 'chevron'}
              size={12}
              style={{ color: 'var(--brass-dim)', flexShrink: 0, marginTop: 3 }}
            />
          )}
        </button>

        {expanded && body && (
          <div style={{
            padding: '0 16px 14px 44px',
            borderTop: '1px solid var(--rule)',
            paddingTop: 12,
          }}>
            <p style={{
              fontFamily: 'var(--font-body)', fontStyle: 'italic',
              fontSize: 14, color: 'var(--ink-dim)', lineHeight: 1.6, margin: 0,
            }}>
              {body}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────
   Arc view
   ──────────────────────────────────────────────────────────── */

function ArcView({ char }: { char: DrupalCharacter }): React.ReactElement {
  const beats = char.majorPlotActions;
  const [expanded, setExpanded] = React.useState<Record<number, boolean>>({});

  const toggle = (i: number): void => setExpanded(p => ({ ...p, [i]: !p[i] }));

  if (beats.length === 0) {
    return <EmptyArc char={char} />;
  }

  return (
    <div style={{ paddingTop: 4 }}>
      {/* Arc meta */}
      <div style={{ marginBottom: 24 }}>
        <div style={{
          display: 'flex', gap: 20, flexWrap: 'wrap', marginBottom: 16,
        }}>
          {[
            { label: 'Beats logged', value: beats.length },
            { label: 'Level', value: char.level != null ? `${char.level}` : '—' },
            { label: 'Campaign', value: char.campaign ?? '—' },
          ].map(stat => (
            <div
              key={stat.label}
              style={{
                background: 'var(--canvas-raised)', border: '1px solid var(--rule)',
                borderRadius: 8, padding: '12px 16px', minWidth: 100,
              }}
            >
              <div style={{
                fontFamily: 'var(--font-display)', fontSize: 9, color: 'var(--ink-dim)',
                letterSpacing: '0.14em', textTransform: 'uppercase', fontWeight: 700, marginBottom: 4,
              }}>
                {stat.label}
              </div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: 22, fontWeight: 700, color: 'var(--brass-bright)' }}>
                {stat.value}
              </div>
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <button
            type="button"
            style={linkBtnStyle}
            onClick={() => {
              const all: Record<number, boolean> = {};
              beats.forEach((_, i) => { all[i] = true; });
              setExpanded(all);
            }}
          >
            Expand all
          </button>
          <span style={{ color: 'var(--ink-faint)' }}>·</span>
          <button type="button" style={linkBtnStyle} onClick={() => setExpanded({})}>
            Collapse all
          </button>
        </div>
      </div>

      {/* Arc spine */}
      <div>
        {beats.map((text, i) => (
          <BeatEntry
            key={i}
            index={i}
            text={text}
            expanded={!!expanded[i]}
            onToggle={() => toggle(i)}
          />
        ))}
        {/* Spine end marker */}
        <div style={{ display: 'grid', gridTemplateColumns: '32px 1fr', gap: 16 }}>
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <div style={{
              width: 8, height: 8, borderRadius: 9999,
              background: 'var(--brass-dim)', opacity: 0.4,
            }} />
          </div>
          <p style={{ fontFamily: 'var(--font-body)', fontStyle: 'italic', fontSize: 12, color: 'var(--ink-faint)', paddingTop: 2 }}>
            Arc continues as new sessions are logged.
          </p>
        </div>
      </div>

      <p style={{
        fontFamily: 'var(--font-body)', fontStyle: 'italic', fontSize: 11,
        color: 'var(--ink-faint)', marginTop: 24,
      }}>
        Showing major plot actions. Full development arc — change tags, before/after deltas,
        and session links — will appear here once <code>field_development[]</code> is wired from Drupal.
      </p>
    </div>
  );
}

const linkBtnStyle: React.CSSProperties = {
  background: 'none', border: 'none', cursor: 'pointer',
  fontFamily: 'var(--font-display)', fontSize: 9, color: 'var(--ink-dim)',
  letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 700, padding: 0,
};

/* ────────────────────────────────────────────────────────────
   Screen
   ──────────────────────────────────────────────────────────── */

export function CharacterDevelopmentScreen({ ctx, setCtx }: ScreenProps): React.ReactElement {
  const data   = useConsoleData();
  const roster = playerCharacters(data);
  const idx    = ctx.charIdx ?? 0;
  const char   = roster[idx] ?? null;

  if (roster.length === 0) {
    return (
      <div className="screen-generic">
        <header className="screen-head">
          <div>
            <span className="reader-eyebrow">Read Stories · Character development</span>
            <h2>Character development</h2>
            <p className="screen-blurb">No characters found for this campaign.</p>
          </div>
        </header>
      </div>
    );
  }

  return (
    <div className="screen-chardetails">
      <CharPicker
        roster={roster}
        selectedId={char?.id ?? null}
        onSelect={id => {
          const i = roster.findIndex(c => c.id === id);
          if (i !== -1) setCtx({ ...ctx, charIdx: i });
        }}
      />

      {char != null && (
        <div className="char-sheet-detail" style={{ flex: 1, overflowY: 'auto', padding: '28px 32px 40px' }}>
          <span className="reader-eyebrow">Read Stories · Character development</span>
          <h2 style={{
            fontFamily: 'var(--font-display)', fontSize: 26, color: 'var(--brass-bright)',
            letterSpacing: '0.04em', margin: '4px 0 4px',
          }}>
            {char.title}
          </h2>
          {char.characterClass != null && (
            <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--ink-dim)', marginBottom: 24 }}>
              {char.characterClass}{char.level != null ? ` · Level ${char.level}` : ''}{char.campaign != null ? ` · ${char.campaign}` : ''}
            </p>
          )}
          <ArcView key={char.id} char={char} />
        </div>
      )}
    </div>
  );
}
