export type DieType = 'd4' | 'd6' | 'd8' | 'd10' | 'd12' | 'd20';

export type GameIconName =
  | 'crossed-swords'
  | 'broadsword'
  | 'arrow-flights'
  | 'shield'
  | 'round-shield'
  | 'magic-swirl'
  | 'fire-spell-cast'
  | 'crystal-ball'
  | 'shadow-follower'
  | 'lightning-arc'
  | 'holy-symbol'
  | 'book-cover'
  | 'concentration-orb'
  | 'muscle-up'
  | 'run'
  | 'heart-plus'
  | 'brain'
  | 'eye'
  | 'charm'
  | 'cowled'
  | 'knight-helmet'
  | 'hood'
  | 'wolf-head'
  | 'holy-grail'
  | 'heart-beats'
  | 'skull'
  | 'poison-bottle'
  | 'burning-passion'
  | 'frozen-orb'
  | 'stars-stack'
  | 'swap-bag'
  | 'gem-pendant'
  | 'ring'
  | 'scroll-unfurled'
  | 'potion-ball';
