from typing import Any, Optional, Sequence

class Voice:
    id: str
    name: str
    languages: Sequence[str]
    gender: Optional[str]
    age: Optional[int]

class Engine:
    def getProperty(self, name: str) -> Any: ...
    def setProperty(self, name: str, value: Any) -> None: ...
    def save_to_file(self, text: str, filename: str) -> None: ...
    def runAndWait(self) -> None: ...
    def stop(self) -> None: ...
    def say(self, text: str, name: str = ...) -> None: ...
    def connect(self, topic: str, callback: Any) -> dict: ...
    def isBusy(self) -> bool: ...

def init(driverName: str = ..., debug: bool = ...) -> Engine: ...
